// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANJR6TlqDh9ymUlZtgQd0Aocfriwt7eHk',
    appId: '1:306534060670:web:b792e318b3a6127c08fe2f',
    messagingSenderId: '306534060670',
    projectId: 'radha-naam-japa',
    authDomain: 'radha-naam-japa.firebaseapp.com',
    storageBucket: 'radha-naam-japa.firebasestorage.app',
    measurementId: 'G-G2W5YG0VRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy7qlJXg_eYz9LxZVz19mFlBVPFUwJb80',
    appId: '1:306534060670:android:a7428355e2cd85cb08fe2f',
    messagingSenderId: '306534060670',
    projectId: 'radha-naam-japa',
    storageBucket: 'radha-naam-japa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG4j0oc2cZz4deTZ89SDb25uDwfvae8TI',
    appId: '1:306534060670:ios:86ee0b6e9800536308fe2f',
    messagingSenderId: '306534060670',
    projectId: 'radha-naam-japa',
    storageBucket: 'radha-naam-japa.firebasestorage.app',
    iosClientId: '306534060670-juobnosuf1h840s82bfhj3pbo9sa9484.apps.googleusercontent.com',
    iosBundleId: 'com.example.radhaNaamJapa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG4j0oc2cZz4deTZ89SDb25uDwfvae8TI',
    appId: '1:306534060670:ios:86ee0b6e9800536308fe2f',
    messagingSenderId: '306534060670',
    projectId: 'radha-naam-japa',
    storageBucket: 'radha-naam-japa.firebasestorage.app',
    iosClientId: '306534060670-juobnosuf1h840s82bfhj3pbo9sa9484.apps.googleusercontent.com',
    iosBundleId: 'com.example.radhaNaamJapa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANJR6TlqDh9ymUlZtgQd0Aocfriwt7eHk',
    appId: '1:306534060670:web:8b79a9c7fce8ae2208fe2f',
    messagingSenderId: '306534060670',
    projectId: 'radha-naam-japa',
    authDomain: 'radha-naam-japa.firebaseapp.com',
    storageBucket: 'radha-naam-japa.firebasestorage.app',
    measurementId: 'G-00136E1FTN',
  );
}
